version: '3'
services:
  gemm-server:
    build: ./
    image: gemm-dev-server:1.0
    container_name: gemm-dev-server
    restart: always
    ports:
      - "80:8080"
    networks:
      - gemm
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - gemm

networks:
  gemm:
    driver: bridge