version: '3'
services:
  gemm-server:
    image: ${ECR_PROD_REGISTRY}/${ECR_PROD_REPOSITORY}:latest
    container_name: gemm-prod-server
    restart: always
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - /home/ubuntu/Pretendard-Medium.otf:/usr/share/fonts/Pretendard-Medium.otf
      - /home/ubuntu/Pretendard-Medium.otf:/app/Pretendard-Medium.otf
    env_file:
      - .env
    networks:
      - gemm

networks:
  gemm:
    driver: bridge
